// Vita3K emulator project
// Copyright (C) 2026 Vita3K team

#include <vita3k_ios/NativeFrontend.h>
#include <vita3k_ios/VirtualController.h>
#include <util/log.h>

// Apple's MacTypes.h declares `typedef char *Ptr;`, which collides with the
// emulator's global Ptr<T> template forward-declared by util/log.h above.
// Rename the MacTypes alias for the framework includes; nothing in this file
// uses it. MacTypes.h is fully included (and include-guarded) inside this
// region, so later transitive includes are no-ops.
#define Ptr MacTypesPtr
#import <AVFoundation/AVFoundation.h>
#import <GameController/GameController.h>
#import <PhotosUI/PhotosUI.h>
#import <QuartzCore/QuartzCore.h>
#import <UIKit/UIKit.h>
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
#include <mach/mach.h>
#undef Ptr

#include <algorithm>
#include <cmath>
#include <mutex>
#include <utility>

#include "vita3k_ios/NativeFrontendInternal.h"
#import "vita3k_ios/TsubomiBridge.h"

// Generated by the Swift compiler from the @objc surface of the Swift sources;
// the name comes from PRODUCT_MODULE_NAME, pinned to "Tsubomi" in
// ios/CMakeLists.txt. This is how the remaining Objective-C++ screens reach
// the migrated SwiftUI ones.
#import "Tsubomi-Swift.h"

namespace {

std::mutex g_action_mutex;
std::optional<Vita3KIOSFrontendAction> g_pending_action;

void queue_action(Vita3KIOSFrontendAction action) {
    const std::lock_guard lock(g_action_mutex);
    g_pending_action = std::move(action);
}

// Last snapshot the core reported, kept so the SwiftUI bridge can read it
// while the library view does not exist (during gameplay). The games vector
// also lets the bridge resolve a title id back to the fields the UI has no
// business knowing about - app_path and trophy_id.
std::mutex g_settings_mutex;
Vita3KIOSSettings g_last_settings;
std::vector<Vita3KIOSGameEntry> g_last_games;

void present_import_picker(BOOL firmware);
void present_license_picker();
void present_save_picker(NSString *titleId);
void reload_library_cells();

} // namespace

// Declared in NativeFrontend.mm's own scope rather than the anonymous
// namespace: -updateGames:settings: calls it from further down the file.
static void vita3k_ios_internal_cache_snapshot(const std::vector<Vita3KIOSGameEntry> &games,
    const Vita3KIOSSettings &settings) {
    const std::lock_guard lock(g_settings_mutex);
    g_last_settings = settings;
    g_last_games = games;
}

// Every observable piece of core state the SwiftUI frontend watches, pushed
// from one place.
//
// This exists because it was previously three separate calls spread across
// -updateGames:settings:, and the firmware push was lost when that method was
// deleted in the library migration - which left onboarding permanently stuck,
// since its per-page gating is exactly what FirmwareState feeds. Keeping the
// three together means a future caller cannot update one and forget another.
static void publish_core_snapshot(const std::vector<Vita3KIOSGameEntry> &games,
    const Vita3KIOSSettings &settings) {
    vita3k_ios_internal_cache_snapshot(games, settings);
    [TsubomiLibraryStateBridge updateWithGames:vita3k_ios_internal::bridge_games()
                                      settings:vita3k_ios_internal::bridge_settings()];
    [TsubomiFirmwareStateBridge updateWithPreinstalledReady:settings.preinstalled_package_ready
                                                  fontReady:settings.font_package_ready
                                          mainFirmwareReady:settings.main_firmware_ready
                                                   allReady:settings.firmware_ready];
}

static void set_metal_drawables_hidden(UIWindow *window, BOOL hidden);

namespace {

UIWindow *active_window() {
    UIWindow *fallback = nil;
    for (UIScene *scene in UIApplication.sharedApplication.connectedScenes) {
        if (![scene isKindOfClass:UIWindowScene.class]
            || scene.activationState == UISceneActivationStateUnattached)
            continue;
        for (UIWindow *window in ((UIWindowScene *)scene).windows) {
            if (window.isKeyWindow)
                return window;
            if (!fallback)
                fallback = window;
        }
    }
    // Session teardown can briefly leave no key window; the library must still
    // find a home instead of silently not appearing (black screen after quit).
    return fallback;
}

void perform_on_main(dispatch_block_t block) {
    if (NSThread.isMainThread)
        block();
    else
        dispatch_async(dispatch_get_main_queue(), block);
}

void present_alert(NSString *title, NSString *message) {
    UIViewController *root = active_window().rootViewController;
    if (!root)
        return;
    UIAlertController *alert = [UIAlertController alertControllerWithTitle:title
                                                                  message:message
                                                           preferredStyle:UIAlertControllerStyleAlert];
    [alert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];
    [root presentViewController:alert animated:YES completion:nil];
}

// Per-title display-name override (a frontend-only rename), keyed by title id.
NSString *title_override_key(NSString *identifier) {
    return [@"tsubomi.title_override." stringByAppendingString:identifier ?: @""];
}

NSString *display_title(NSString *identifier, NSString *original) {
    NSString *override = [NSUserDefaults.standardUserDefaults stringForKey:title_override_key(identifier)];
    return override.length ? override : original;
}

// The library metadata visibility toggles (title IDs, version, size) are read
// directly by the SwiftUI cells through @AppStorage - see DefaultsKey in
// DefaultsToggle.swift, which pins the same keys and the same default-ON
// behaviour. Nothing on this side reads them any more.

// Untinted Regular glass. Apple's guidance is to tint the *primary action*
// only — a global wash applied to every surface flattens the hierarchy and
// fights the material's own adaptive tinting, so the former white/black wash
// is gone. Use glass_effect_tinted() for the one call-to-action per screen.
//
// Both variants are cached: UIGlassEffect instances are immutable once
// configured and a UIVisualEffectView rebuilds its whole backdrop when -effect
// is assigned, so handing out a fresh object per call made cell reuse pay for
// a full effect teardown on every dequeue.
UIVisualEffect *glass_effect(const BOOL interactive = YES) {
    static UIGlassEffect *live = nil;
    static UIGlassEffect *stat = nil;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        live = [UIGlassEffect effectWithStyle:UIGlassEffectStyleRegular];
        live.interactive = YES;
        stat = [UIGlassEffect effectWithStyle:UIGlassEffectStyleRegular];
        stat.interactive = NO;
    });
    return interactive ? live : stat;
}

// Tinted glass for the one element per screen that should stand out. Callers
// pass `interactive` only for a control the user actually presses; static
// banners leave it off so they cost a single composite instead of a live
// refraction pass.
UIVisualEffect *glass_effect_tinted(UIColor *tint, const BOOL interactive = NO) {
    UIGlassEffect *effect = [UIGlassEffect effectWithStyle:UIGlassEffectStyleRegular];
    effect.interactive = interactive;
    effect.tintColor = tint;
    return effect;
}

// Liquid Glass shapes use continuous ("squircle") corners, not circular arcs.
// Every rounded surface in the app goes through here so the curvature matches
// the system's own glass containers.
void round_continuous(UIView *view, const CGFloat radius) {
    view.layer.cornerRadius = radius;
    view.layer.cornerCurve = kCACornerCurveContinuous;
}

// ---- Cover art cache --------------------------------------------------------
// Cells used to call -imageWithContentsOfFile: on every dequeue, so scrolling
// the library re-read and re-decoded a PNG per cell per frame on the main
// thread — the app's main source of scroll jank and of CPU wake-ups while
// simply browsing. Decode once off-main, keep the decoded bitmap in an NSCache
// (the system evicts it under pressure), and hand cells the ready image.

NSCache<NSString *, UIImage *> *cover_cache() {
    static NSCache<NSString *, UIImage *> *cache = nil;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        cache = [[NSCache alloc] init];
        cache.countLimit = 240;
        // Evict on memory warnings rather than competing with the emulator's
        // guest allocations.
        [NSNotificationCenter.defaultCenter
            addObserverForName:UIApplicationDidReceiveMemoryWarningNotification
                        object:nil
                         queue:NSOperationQueue.mainQueue
                    usingBlock:^(__unused NSNotification *note) { [cache removeAllObjects]; }];
    });
    return cache;
}

void invalidate_cover_cache(NSString *path) {
    if (path.length)
        [cover_cache() removeObjectForKey:path];
    else
        [cover_cache() removeAllObjects];
}

// Cached decode. Returns the image immediately when it is already resident;
// otherwise decodes on a background queue and invokes `ready` on the main
// thread. `ready` is not called when the image was returned synchronously.
UIImage *cover_image(NSString *path, void (^ready)(UIImage *)) {
    if (!path.length)
        return nil;
    if (UIImage *cached = [cover_cache() objectForKey:path])
        return cached;
    static dispatch_queue_t queue = nil;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        queue = dispatch_queue_create("tsubomi.covers", DISPATCH_QUEUE_SERIAL);
    });
    NSString *key = [path copy];
    dispatch_async(queue, ^{
        UIImage *image = [UIImage imageWithContentsOfFile:key];
        // Force the decode here instead of on the first draw, which is what
        // actually stalls the render loop mid-scroll.
        if (image)
            image = [image imageByPreparingForDisplay] ?: image;
        if (!image) {
            LOG_ERROR("iOS library art could not be decoded at '{}'", key.UTF8String);
            // Still report completion: callers that bridge this to an async
            // await would otherwise never resume. Callers keep their
            // placeholder by ignoring a nil result.
            dispatch_async(dispatch_get_main_queue(), ^{
                if (ready)
                    ready(nil);
            });
            return;
        }
        [cover_cache() setObject:image forKey:key];
        dispatch_async(dispatch_get_main_queue(), ^{
            if (ready)
                ready(image);
        });
    });
    return nil;
}

// ---- Custom cover art -------------------------------------------------------
// Users can replace a game's library art with a photo. The picked original is
// kept so the crop can be re-adjusted later; the rendered square cover is what
// cells actually display.

NSString *covers_directory() {
    NSString *documents = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES).firstObject;
    NSString *directory = [documents stringByAppendingPathComponent:@"Tsubomi/covers"];
    [NSFileManager.defaultManager createDirectoryAtPath:directory
                            withIntermediateDirectories:YES attributes:nil error:nil];
    return directory;
}

NSString *cover_original_path(NSString *titleId) {
    return [covers_directory() stringByAppendingPathComponent:
        [NSString stringWithFormat:@"%@-original.png", titleId]];
}

NSString *cover_render_path(NSString *titleId) {
    return [covers_directory() stringByAppendingPathComponent:
        [NSString stringWithFormat:@"%@-cover.png", titleId]];
}

BOOL has_custom_cover(NSString *titleId) {
    return [NSFileManager.defaultManager fileExistsAtPath:cover_render_path(titleId)];
}

// ---- Per-game settings ------------------------------------------------------
// Overrides are a defaults dictionary per title; absent = use global settings.

NSString *game_settings_key(NSString *titleId) {
    return [@"tsubomi.gameSettings." stringByAppendingString:titleId ?: @""];
}

BOOL has_game_settings(NSString *titleId) {
    return [NSUserDefaults.standardUserDefaults dictionaryForKey:game_settings_key(titleId)] != nil;
}

Vita3KIOSSettings game_settings_or(NSString *titleId, const Vita3KIOSSettings &fallback) {
    NSDictionary *stored = [NSUserDefaults.standardUserDefaults dictionaryForKey:game_settings_key(titleId)];
    if (!stored)
        return fallback;
    Vita3KIOSSettings settings = fallback;
    if (stored[@"resolution"])
        settings.resolution_multiplier = [stored[@"resolution"] floatValue];
    if (stored[@"vsync"])
        settings.v_sync = [stored[@"vsync"] boolValue];
    settings.fps_limit = 60;
    if (stored[@"cpuOpt"])
        settings.cpu_opt = [stored[@"cpuOpt"] boolValue];
    if (stored[@"ngs"])
        settings.ngs_enable = [stored[@"ngs"] boolValue];
    if (stored[@"asyncPipelines"])
        settings.async_pipeline_compilation = [stored[@"asyncPipelines"] boolValue];
    if (stored[@"anisotropic"])
        settings.anisotropic_filtering = [stored[@"anisotropic"] intValue];
    if (stored[@"highAccuracy"])
        settings.high_accuracy = [stored[@"highAccuracy"] boolValue];
    if (stored[@"surfaceSync"])
        settings.surface_sync = [stored[@"surfaceSync"] boolValue];
    // Absent for titles last saved before the switch existed; those fall back
    // to the global value carried in `fallback`.
    if (stored[@"doubleBuffer"])
        settings.double_buffer = [stored[@"doubleBuffer"] boolValue];
    return settings;
}

void store_game_settings(NSString *titleId, const Vita3KIOSSettings &settings) {
    [NSUserDefaults.standardUserDefaults setObject:@{
        @"resolution": @(settings.resolution_multiplier),
        @"vsync": @(settings.v_sync),
        @"cpuOpt": @(settings.cpu_opt),
        @"ngs": @(settings.ngs_enable),
        @"asyncPipelines": @(settings.async_pipeline_compilation),
        @"anisotropic": @(settings.anisotropic_filtering),
        @"highAccuracy": @(settings.high_accuracy),
        @"surfaceSync": @(settings.surface_sync),
        @"doubleBuffer": @(settings.double_buffer),
    } forKey:game_settings_key(titleId)];
}

} // namespace

namespace {
// Defined further down the file, past this block.
std::string hex_bytes(const std::string &value);
} // namespace
static void present_cover_crop(NSString *titleId, UIImage *image);
static void present_cover_picker(NSString *titleId);

// The seam TsubomiBridge.mm uses; see NativeFrontendInternal.h. Thin
// forwarders so the storage details above stay file-local.
namespace vita3k_ios_internal {

void queue_frontend_action(Vita3KIOSFrontendAction action) {
    queue_action(std::move(action));
}

Vita3KIOSSettings current_global_settings() {
    const std::lock_guard lock(g_settings_mutex);
    return g_last_settings;
}

Vita3KIOSSettings load_title_settings(NSString *title_id, const Vita3KIOSSettings &fallback) {
    return game_settings_or(title_id, fallback);
}

void store_title_settings(NSString *title_id, const Vita3KIOSSettings &settings) {
    store_game_settings(title_id, settings);
}

void clear_title_settings(NSString *title_id) {
    [NSUserDefaults.standardUserDefaults removeObjectForKey:game_settings_key(title_id)];
}

UIImage *cached_art(NSString *path, void (^ready)(UIImage *)) {
    return cover_image(path, ready);
}

void present_firmware_picker() {
    present_import_picker(YES);
}

void reload_library() {
    reload_library_cells();
}

NSString *display_title_for(NSString *title_id, NSString *original) {
    return display_title(title_id, original);
}

void set_display_title(NSString *title_id, NSString *title) {
    NSUserDefaults *defaults = NSUserDefaults.standardUserDefaults;
    // An empty rename clears the override so the packaged title returns.
    if (title.length)
        [defaults setObject:title forKey:title_override_key(title_id)];
    else
        [defaults removeObjectForKey:title_override_key(title_id)];
}

bool title_has_custom_cover(NSString *title_id) {
    return has_custom_cover(title_id);
}

NSString *custom_cover_path(NSString *title_id) {
    return cover_render_path(title_id);
}

bool title_has_settings(NSString *title_id) {
    return has_game_settings(title_id);
}

std::string hex_bytes_for_log(const std::string &value) {
    return hex_bytes(value);
}

std::vector<Vita3KIOSGameEntry> current_games() {
    const std::lock_guard lock(g_settings_mutex);
    return g_last_games;
}

std::optional<Vita3KIOSGameEntry> game_for_title(NSString *title_id) {
    const std::string wanted = title_id.UTF8String ? title_id.UTF8String : "";
    const std::lock_guard lock(g_settings_mutex);
    for (const auto &game : g_last_games) {
        if (game.title_id == wanted)
            return game;
    }
    return std::nullopt;
}

void present_game_picker() {
    present_import_picker(NO);
}

void present_license_import_picker() {
    present_license_picker();
}

void present_save_import_picker(NSString *title_id) {
    present_save_picker(title_id);
}

void present_cover_art_picker(NSString *title_id) {
    present_cover_picker(title_id);
}

void present_cover_crop_editor(NSString *title_id) {
    // Re-crop the previously picked original when there is one, otherwise the
    // game's packaged art, so the built-in cover can be reframed too.
    UIImage *source = [UIImage imageWithContentsOfFile:cover_original_path(title_id)];
    if (!source) {
        const auto game = game_for_title(title_id);
        if (game)
            source = [UIImage imageWithContentsOfFile:
                [NSString stringWithUTF8String:game->icon_path.c_str()] ?: @""];
    }
    present_cover_crop(title_id, source);
}

bool firmware_ready_or_alert() {
    const auto settings = current_global_settings();
    if (settings.firmware_ready)
        return true;
    NSString *missing = [NSString stringWithUTF8String:settings.missing_firmware.c_str()]
        ?: @"required firmware";
    present_alert(@"Complete firmware setup",
        [NSString stringWithFormat:
            @"Install all three firmware packages before importing or playing games.\n\nMissing: %@\n\nUse + > Import firmware (.PUP).",
            missing]);
    return false;
}

void present_settings_sheet(NSString *title_id, NSString *display_name) {
    UIViewController *root = active_window().rootViewController;
    if (!root || root.presentedViewController)
        return;
    // Belt and braces: a lingering game drawable must never be visible under
    // the settings sheet.
    set_metal_drawables_hidden(active_window(), YES);
    UIViewController *controller = title_id.length
        ? [TsubomiSettingsHost settingsViewControllerForTitle:title_id
                                                  displayName:display_name
                                               dismissHandler:^{}]
        : [TsubomiSettingsHost globalSettingsViewControllerWithDismissHandler:^{
              // The core applies the change on its own thread and reports
              // restart-required fields through the status toast.
              Vita3KIOSFrontendAction action;
              action.kind = Vita3KIOSFrontendActionKind::Refresh;
              queue_action(std::move(action));
          }];
    [root presentViewController:controller animated:YES completion:nil];
}

void show_jit_required_alert() {
    present_alert(@"JIT required",
        @"Open StikDebug, enable JIT, and keep it attached until Tsubomi finishes Preparing JIT.");
}

void show_graphics_help() {
    present_alert(@"Graphics help",
        @"If a game's shaders or textures do not look correct, open that game's settings and try Graphics > High accuracy. "
        @"If lighting appears white or missing, also enable Graphics > Surface sync. "
        @"If character models look shattered or garbled, make sure Graphics > Double buffer is off.");
}

void invalidate_cached_art(NSString *path) {
    invalidate_cover_cache(path);
}

} // namespace vita3k_ios_internal

namespace {

std::string hex_bytes(const std::string &value) {
    constexpr char digits[] = "0123456789ABCDEF";
    std::string result;
    result.reserve(value.size() * 3);
    for (const unsigned char byte : value) {
        if (!result.empty())
            result.push_back(' ');
        result.push_back(digits[byte >> 4]);
        result.push_back(digits[byte & 0x0F]);
    }
    return result;
}

} // namespace

// Pan/zoom square crop for custom cover art. The scroll view's visible square
// maps directly to the rendered 1024x1024 cover.
@interface Vita3KCoverCropController : UIViewController <UIScrollViewDelegate>
@property(nonatomic, strong) UIImage *image;
@property(nonatomic, copy) NSString *titleId;
@property(nonatomic, copy) dispatch_block_t onDone;
@property(nonatomic, strong) UIScrollView *cropScroll;
@property(nonatomic, strong) UIImageView *imageView;
@end

@implementation Vita3KCoverCropController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = UIColor.blackColor;

    self.cropScroll = [[UIScrollView alloc] init];
    self.cropScroll.delegate = self;
    self.cropScroll.showsHorizontalScrollIndicator = NO;
    self.cropScroll.showsVerticalScrollIndicator = NO;
    self.cropScroll.alwaysBounceHorizontal = YES;
    self.cropScroll.alwaysBounceVertical = YES;
    self.cropScroll.layer.borderColor = UIColor.whiteColor.CGColor;
    self.cropScroll.layer.borderWidth = 1.5;
    self.cropScroll.clipsToBounds = YES;
    [self.view addSubview:self.cropScroll];

    self.imageView = [[UIImageView alloc] initWithImage:self.image];
    self.imageView.contentMode = UIViewContentModeScaleToFill;
    [self.cropScroll addSubview:self.imageView];

    UILabel *hint = [[UILabel alloc] init];
    hint.text = @"Pinch and drag to frame the cover";
    hint.textColor = UIColor.whiteColor;
    hint.font = [UIFont systemFontOfSize:15 weight:UIFontWeightSemibold];
    hint.textAlignment = NSTextAlignmentCenter;
    hint.tag = 401;
    [self.view addSubview:hint];

    UIButton *cancel = [UIButton buttonWithType:UIButtonTypeSystem];
    [cancel setTitle:@"Cancel" forState:UIControlStateNormal];
    cancel.tintColor = UIColor.whiteColor;
    cancel.tag = 402;
    [cancel addTarget:self action:@selector(cancelTapped) forControlEvents:UIControlEventTouchUpInside];
    [self.view addSubview:cancel];

    UIButton *save = [UIButton buttonWithType:UIButtonTypeSystem];
    [save setTitle:@"Save" forState:UIControlStateNormal];
    save.titleLabel.font = [UIFont systemFontOfSize:17 weight:UIFontWeightSemibold];
    save.tag = 403;
    [save addTarget:self action:@selector(saveTapped) forControlEvents:UIControlEventTouchUpInside];
    [self.view addSubview:save];
}

- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    const UIEdgeInsets safe = self.view.safeAreaInsets;
    const CGRect bounds = self.view.bounds;
    const CGFloat side = MIN(CGRectGetWidth(bounds) - 40,
        CGRectGetHeight(bounds) - safe.top - safe.bottom - 140);
    const BOOL firstLayout = CGRectIsEmpty(self.cropScroll.frame);
    self.cropScroll.frame = CGRectMake((CGRectGetWidth(bounds) - side) / 2,
        safe.top + 64, side, side);
    [self.view viewWithTag:401].frame = CGRectMake(20, safe.top + 18, CGRectGetWidth(bounds) - 40, 24);
    [self.view viewWithTag:402].frame = CGRectMake(24, CGRectGetMaxY(self.cropScroll.frame) + 18, 90, 44);
    [self.view viewWithTag:403].frame = CGRectMake(CGRectGetWidth(bounds) - 114,
        CGRectGetMaxY(self.cropScroll.frame) + 18, 90, 44);
    if (firstLayout && self.image) {
        const CGSize imageSize = self.image.size;
        // Minimum zoom always fills the square.
        const CGFloat fill = MAX(side / imageSize.width, side / imageSize.height);
        self.imageView.frame = CGRectMake(0, 0, imageSize.width, imageSize.height);
        self.cropScroll.contentSize = imageSize;
        self.cropScroll.minimumZoomScale = fill;
        self.cropScroll.maximumZoomScale = MAX(fill * 8, 2.0);
        self.cropScroll.zoomScale = fill;
        // Center the initial crop.
        self.cropScroll.contentOffset = CGPointMake(
            MAX(0, (imageSize.width * fill - side) / 2),
            MAX(0, (imageSize.height * fill - side) / 2));
    }
}

- (UIView *)viewForZoomingInScrollView:(UIScrollView *)scrollView {
    (void)scrollView;
    return self.imageView;
}

- (void)cancelTapped {
    [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)saveTapped {
    const CGFloat side = CGRectGetWidth(self.cropScroll.bounds);
    const CGFloat zoom = self.cropScroll.zoomScale;
    const CGRect cropInImage = CGRectMake(self.cropScroll.contentOffset.x / zoom,
        self.cropScroll.contentOffset.y / zoom, side / zoom, side / zoom);
    const CGFloat renderSide = 1024;
    UIGraphicsImageRendererFormat *format = [UIGraphicsImageRendererFormat preferredFormat];
    format.opaque = YES;
    UIGraphicsImageRenderer *renderer = [[UIGraphicsImageRenderer alloc]
        initWithSize:CGSizeMake(renderSide, renderSide) format:format];
    UIImage *image = self.image;
    UIImage *rendered = [renderer imageWithActions:^(__unused UIGraphicsImageRendererContext *context) {
        const CGFloat scale = renderSide / cropInImage.size.width;
        [image drawInRect:CGRectMake(-cropInImage.origin.x * scale, -cropInImage.origin.y * scale,
            image.size.width * scale, image.size.height * scale)];
    }];
    [UIImagePNGRepresentation(rendered) writeToFile:cover_render_path(self.titleId) atomically:YES];
    invalidate_cover_cache(cover_render_path(self.titleId));
    dispatch_block_t done = self.onDone;
    [self dismissViewControllerAnimated:YES completion:^{
        if (done)
            done();
    }];
}

@end

// Keeps the PHPicker delegate alive while the sheet is up; on pick, stores the
// original and opens the crop controller.
@interface Vita3KCoverPicker : NSObject <PHPickerViewControllerDelegate>
@property(nonatomic, copy) NSString *titleId;
@end

static Vita3KCoverPicker *g_cover_picker = nil;
static void present_cover_crop(NSString *titleId, UIImage *image);

@implementation Vita3KCoverPicker

- (void)picker:(PHPickerViewController *)picker didFinishPicking:(NSArray<PHPickerResult *> *)results {
    NSString *titleId = self.titleId;
    [picker dismissViewControllerAnimated:YES completion:nil];
    NSItemProvider *provider = results.firstObject.itemProvider;
    if (![provider canLoadObjectOfClass:UIImage.class])
        return;
    [provider loadObjectOfClass:UIImage.class completionHandler:^(id<NSItemProviderReading> object, NSError *error) {
        UIImage *image = (UIImage *)object;
        if (!image || error)
            return;
        dispatch_async(dispatch_get_main_queue(), ^{
            [UIImagePNGRepresentation(image) writeToFile:cover_original_path(titleId) atomically:YES];
            present_cover_crop(titleId, image);
        });
    }];
}

@end

static void present_cover_crop(NSString *titleId, UIImage *image) {
    UIViewController *root = active_window().rootViewController;
    if (!root || !image)
        return;
    Vita3KCoverCropController *crop = [[Vita3KCoverCropController alloc] init];
    crop.image = image;
    crop.titleId = titleId;
    crop.onDone = ^{ reload_library_cells(); };
    crop.modalPresentationStyle = UIModalPresentationFullScreen;
    [root presentViewController:crop animated:YES completion:nil];
}

static void present_cover_picker(NSString *titleId) {
    UIViewController *root = active_window().rootViewController;
    if (!root)
        return;
    PHPickerConfiguration *configuration = [[PHPickerConfiguration alloc] init];
    configuration.selectionLimit = 1;
    configuration.filter = PHPickerFilter.imagesFilter;
    PHPickerViewController *picker = [[PHPickerViewController alloc] initWithConfiguration:configuration];
    if (!g_cover_picker)
        g_cover_picker = [[Vita3KCoverPicker alloc] init];
    g_cover_picker.titleId = titleId;
    picker.delegate = g_cover_picker;
    [root presentViewController:picker animated:YES completion:nil];
}


// The SwiftUI library (TsubomiLibraryHost). Retained here because only its
// view is installed in the hierarchy; its content comes from LibraryState,
// which the core pushes into through TsubomiLibraryStateBridge.
static UIViewController *g_library_controller = nil;
// Onboarding is added over the library's view, so it is retained alongside it.
static UIViewController *g_onboarding_controller = nil;

// Convenience for the many call sites that only want the library's view.
static UIView *library_view() {
    return g_library_controller.view;
}
// Last-known JIT availability, applied whenever the library is (re)shown so the
// banner is correct even across library rebuilds between game sessions.
static BOOL g_jit_available = YES;
// A quit game's SDL/Metal drawable can be torn down over several runloop
// ticks, not just the one after vita3k_ios_show_library reasserts visibility
// - if settings gets opened (or the library redraws) in that window, the
// one-shot hide can miss a drawable that gets (re)added moments later,
// showing a frozen frame of the game that was just quit behind the UI.
// Re-run the hide pass on a short repeating timer for as long as the library
// is on screen instead of relying on a single reassertion.
static NSTimer *g_library_metal_hide_timer = nil;
// Set once the very first library presentation of this process has played its
// launch intro. Returning to the library after quitting a game recreates the
// controller too (vita3k_ios_hide_library nils it out), so this can't just be
// a null check or every game-to-library transition would replay the intro.
static BOOL g_app_launch_intro_shown = NO;

namespace {
void reload_library_cells() {
    // The library display toggles (title IDs, version, size) are read straight
    // from NSUserDefaults by the SwiftUI cells via @AppStorage, so those
    // re-render themselves. This re-derives the entries for the changes that
    // are not observable that way - a new custom cover, or a rename.
    [TsubomiLibraryStateBridge refreshEntries];
}
} // namespace


// Game-controller navigation for the native UI.
//
// This used to walk g_library's UIView subtree, collect focusable views, and
// move a focus ring spatially. The library is SwiftUI now and has no such
// subtree, so the navigator is reduced to what it should always have been: it
// reads the controller and forwards intent. LibraryState owns which game is
// focused and maps D-pad movement onto whichever presentation is showing (see
// LibraryState.FocusLayout); the view draws the ring and scrolls it into view.
//
// Handlers no-op whenever the library is off screen, so in-game input is never
// intercepted.
@interface Vita3KPadNavigator : NSObject
@property(nonatomic) BOOL active;
+ (instancetype)shared;
- (void)start;
- (void)stop;
@end

@implementation Vita3KPadNavigator

+ (instancetype)shared {
    static Vita3KPadNavigator *navigator;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        navigator = [[Vita3KPadNavigator alloc] init];
        [NSNotificationCenter.defaultCenter addObserverForName:GCControllerDidConnectNotification
                                                        object:nil
                                                         queue:NSOperationQueue.mainQueue
                                                    usingBlock:^(NSNotification *note) {
            [navigator wireController:note.object];
        }];
    });
    return navigator;
}

- (void)start {
    self.active = YES;
    for (GCController *controller in GCController.controllers)
        [self wireController:controller];
}

- (void)stop {
    self.active = NO;
    [TsubomiLibraryStateBridge clearFocus];
}

- (void)wireController:(GCController *)controller {
    GCExtendedGamepad *pad = controller.extendedGamepad;
    if (!pad)
        return;
    __weak Vita3KPadNavigator *weakSelf = self;
    pad.dpad.up.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf moveX:0 y:-1];
    };
    pad.dpad.down.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf moveX:0 y:1];
    };
    pad.dpad.left.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf moveX:-1 y:0];
    };
    pad.dpad.right.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf moveX:1 y:0];
    };
    pad.buttonA.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf activate];
    };
    pad.buttonB.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf back];
    };
    pad.buttonY.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf gameActions];
    };
    // L1/R1 cycled the old settings screen's categories. The SwiftUI settings
    // screen is one scrolling Form, so there is nothing to cycle; the handlers
    // are cleared rather than left pointing at a removed method.
    pad.leftShoulder.pressedChangedHandler = nil;
    pad.rightShoulder.pressedChangedHandler = nil;
}

// The library is driveable only while it is on screen and nothing is presented
// over it. A presented sheet (settings, trophies) is SwiftUI's to handle.
- (BOOL)navigationAllowed {
    UIWindow *window = library_view().window;
    return self.active && window != nil
        && window.rootViewController.presentedViewController == nil;
}

- (void)moveX:(NSInteger)dx y:(NSInteger)dy {
    if (![self navigationAllowed])
        return;
    [TsubomiLibraryStateBridge moveFocusByX:dx y:dy];
}

- (void)activate {
    if (![self navigationAllowed])
        return;
    [TsubomiLibraryStateBridge activateFocused];
}

- (void)gameActions {
    if (![self navigationAllowed])
        return;
    [TsubomiLibraryStateBridge showActionsForFocused];
}

- (void)back {
    if (!self.active)
        return;
    UIWindow *window = library_view().window;
    UIViewController *presented = window.rootViewController.presentedViewController;
    if (presented) {
        [presented dismissViewControllerAnimated:YES completion:nil];
        return;
    }
    // Nothing presented: drop the focus ring so the library returns to its
    // touch-driven appearance.
    [TsubomiLibraryStateBridge clearFocus];
}

@end

// Presents the Files picker and hands the copied file to the emulator loop.
@interface Vita3KImportPicker : NSObject <UIDocumentPickerDelegate>
@property(nonatomic) Vita3KIOSFrontendActionKind kind;
@property(nonatomic, copy) NSString *titleId;
@end

@implementation Vita3KImportPicker

- (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls {
    (void)controller;
    NSURL *url = urls.firstObject;
    if (!url)
        return;
    const BOOL scoped = [url startAccessingSecurityScopedResource];
    NSString *documents = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES).firstObject;
    NSString *importDir = [[documents stringByAppendingPathComponent:@"Tsubomi"] stringByAppendingPathComponent:@"import"];
    [NSFileManager.defaultManager createDirectoryAtPath:importDir withIntermediateDirectories:YES attributes:nil error:nil];
    NSString *destination = [importDir stringByAppendingPathComponent:url.lastPathComponent];
    [NSFileManager.defaultManager removeItemAtPath:destination error:nil];
    NSError *error = nil;
    const BOOL copied = [NSFileManager.defaultManager copyItemAtURL:url
                                                              toURL:[NSURL fileURLWithPath:destination]
                                                              error:&error];
    if (scoped)
        [url stopAccessingSecurityScopedResource];
    if (!copied) {
        // A common cause is an iCloud-only file whose contents were never
        // downloaded, or insufficient free space for the working copy. Surface
        // the underlying reason instead of a bare "could not copy".
        const char *reason = error.localizedDescription.UTF8String ?: "unknown error";
        LOG_ERROR("iOS import copy failed for '{}': {}",
            url.lastPathComponent.UTF8String ?: "?", reason);
        vita3k_ios_report_import_result(
            std::string("Could not read the selected file: ") + reason
                + ". If it is stored in iCloud, download it in Files first.",
            false);
        return;
    }
    NSString *busy = @"Installing game…";
    if (self.kind == Vita3KIOSFrontendActionKind::ImportFirmware)
        busy = @"Installing firmware…";
    else if (self.kind == Vita3KIOSFrontendActionKind::ImportLicense)
        busy = @"Installing license…";
    else if (self.kind == Vita3KIOSFrontendActionKind::ImportSave)
        busy = @"Importing save…";
    [TsubomiLibraryStateBridge setBusyMessage:busy];
    Vita3KIOSFrontendAction action;
    action.kind = self.kind;
    action.app_path = destination.UTF8String;
    action.title_id = self.titleId.UTF8String ?: "";
    queue_action(std::move(action));
}

@end

static Vita3KImportPicker *g_import_picker = nil;

namespace {

// Presents the Files picker for a game/firmware/license import. Attached to the
// + button's UIMenu (games/firmware) and the post-install license prompt.
void present_import_picker(BOOL firmware) {
    UIViewController *root = active_window().rootViewController;
    if (!root)
        return;
    if (!g_import_picker)
        g_import_picker = [[Vita3KImportPicker alloc] init];
    g_import_picker.kind = firmware ? Vita3KIOSFrontendActionKind::ImportFirmware
                                    : Vita3KIOSFrontendActionKind::ImportGame;
    g_import_picker.titleId = nil;
    NSMutableArray<UTType *> *types = [NSMutableArray array];
    if (firmware) {
        UTType *pup = [UTType typeWithFilenameExtension:@"pup"];
        if (pup)
            [types addObject:pup];
    } else {
        [types addObject:UTTypeZIP];
        UTType *vpk = [UTType typeWithFilenameExtension:@"vpk"];
        if (vpk)
            [types addObject:vpk];
        UTType *pkg = [UTType typeWithFilenameExtension:@"pkg"];
        if (pkg)
            [types addObject:pkg];
    }
    [types addObject:UTTypeData];
    UIDocumentPickerViewController *picker =
        [[UIDocumentPickerViewController alloc] initForOpeningContentTypes:types];
    picker.delegate = g_import_picker;
    picker.allowsMultipleSelection = NO;
    [root presentViewController:picker animated:YES completion:nil];
}

void present_license_picker() {
    UIViewController *root = active_window().rootViewController;
    if (!root)
        return;
    if (!g_import_picker)
        g_import_picker = [[Vita3KImportPicker alloc] init];
    g_import_picker.kind = Vita3KIOSFrontendActionKind::ImportLicense;
    g_import_picker.titleId = nil;
    // A work.bin has no standard UTType; accept any file.
    UIDocumentPickerViewController *picker =
        [[UIDocumentPickerViewController alloc] initForOpeningContentTypes:@[UTTypeData]];
    picker.delegate = g_import_picker;
    picker.allowsMultipleSelection = NO;
    [root presentViewController:picker animated:YES completion:nil];
}

void present_save_picker(NSString *titleId) {
    UIViewController *root = active_window().rootViewController;
    if (!root)
        return;
    if (!g_import_picker)
        g_import_picker = [[Vita3KImportPicker alloc] init];
    g_import_picker.kind = Vita3KIOSFrontendActionKind::ImportSave;
    g_import_picker.titleId = titleId;
    UIDocumentPickerViewController *picker =
        [[UIDocumentPickerViewController alloc] initForOpeningContentTypes:@[UTTypeZIP, UTTypeData]];
    picker.delegate = g_import_picker;
    picker.allowsMultipleSelection = NO;
    [root presentViewController:picker animated:YES completion:nil];
}

} // namespace

// Hide or reveal every CAMetalLayer-backed view under the window. The SDL
// drawable keeps the last presented game frame after a session ends, and it
// can bleed into library/settings backgrounds through composition paths that
// don't show up in screenshots. While the library UI is on screen nothing
// renders into it, so hiding it outright is safe.
static void set_metal_drawables_hidden(UIWindow *window, BOOL hidden) {
    if (!window)
        return;
    // Walk the entire window: SDL's drawable normally lives under the root
    // view controller, but a drawable parented to the window itself must be
    // caught too or it keeps showing the last game frame behind settings.
    NSMutableArray<UIView *> *pending = [NSMutableArray arrayWithObject:window];
    while (pending.count) {
        UIView *view = pending.lastObject;
        [pending removeLastObject];
        if ([view.layer isKindOfClass:CAMetalLayer.class]) {
            // Never hide a view the library lives inside: hiding an ancestor
            // hides the library with it and the whole screen goes black.
            if (hidden && library_view() && [library_view() isDescendantOfView:view]) {
                [pending addObjectsFromArray:view.subviews];
                continue;
            }
            view.hidden = hidden;
            continue;
        }
        [pending addObjectsFromArray:view.subviews];
    }
}

void vita3k_ios_show_library(const std::vector<Vita3KIOSGameEntry> &games,
    const Vita3KIOSSettings &settings) {
    const std::vector<Vita3KIOSGameEntry> gamesCopy = games;
    const Vita3KIOSSettings settingsCopy = settings;
    perform_on_main(^{
        UIWindow *window = active_window();
        if (!window)
            return;
        // Host the library under the root view controller's view, not directly
        // on the window. UIButton context menus (the + import menu) need a view
        // controller in the responder chain to present from; a view parented
        // straight to the window has none, so taps did nothing.
        // Host the library under the root view controller's view, not
        // directly on the window: SwiftUI menus and sheets need a view
        // controller in the responder chain to present from.
        UIViewController *rootController = window.rootViewController;
        UIView *host = rootController.view ?: window;
        BOOL playLaunchIntro = NO;
        if (!g_library_controller) {
            g_library_controller = [TsubomiLibraryHost libraryViewController];
            // Proper containment, so the hosting controller receives
            // appearance and trait callbacks and can present sheets itself.
            if (rootController)
                [rootController addChildViewController:g_library_controller];
            [host addSubview:library_view()];
            if (rootController)
                [g_library_controller didMoveToParentViewController:rootController];
            if (!g_app_launch_intro_shown) {
                playLaunchIntro = YES;
                g_app_launch_intro_shown = YES;
            }
        } else if (library_view().superview != host) {
            [host addSubview:library_view()];
        }
        library_view().frame = host.bounds;
        library_view().autoresizingMask =
            UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
        library_view().hidden = NO;
        if (playLaunchIntro) {
            // Cold app launch dropped the library on screen with no
            // transition at all. A short fade + gentle scale-up reads as an
            // intentional entrance instead of the UI just appearing.
            library_view().alpha = 0.0;
            library_view().transform = CGAffineTransformMakeScale(0.96, 0.96);
        }
        publish_core_snapshot(gamesCopy, settingsCopy);
        [TsubomiLibraryStateBridge setJITAvailable:g_jit_available];
        NSUserDefaults *defaults = NSUserDefaults.standardUserDefaults;
        if (settingsCopy.firmware_ready) {
            // Existing installs that already contain all three packages never
            // see onboarding, even when upgrading from a build predating it.
            [defaults setBool:YES forKey:@"tsubomi.onboarded"];
            [g_onboarding_controller.view removeFromSuperview];
            g_onboarding_controller = nil;
        } else if (![defaults boolForKey:@"tsubomi.onboarded"] || !settingsCopy.firmware_ready) {
            if (!g_onboarding_controller) {
                // Firmware progress reaches the flow through FirmwareState,
                // pushed from the same snapshot above, so there is no
                // equivalent of the old updateFirmwareSettings: call here.
                g_onboarding_controller =
                    [TsubomiOnboardingHost onboardingViewControllerWithFinishHandler:^{
                        [UIView animateWithDuration:0.3 animations:^{
                            g_onboarding_controller.view.alpha = 0;
                        } completion:^(__unused BOOL finished) {
                            [g_onboarding_controller.view removeFromSuperview];
                            g_onboarding_controller = nil;
                        }];
                    }];
                UIView *onboarding = g_onboarding_controller.view;
                onboarding.frame = library_view().bounds;
                onboarding.autoresizingMask =
                    UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
                [library_view() addSubview:onboarding];
            }
            [library_view() bringSubviewToFront:g_onboarding_controller.view];
        }
        [library_view().superview bringSubviewToFront:library_view()];
        set_metal_drawables_hidden(window, YES);
        [Vita3KPadNavigator.shared start];
        if (playLaunchIntro) {
            UIView *introTarget = library_view();
            [UIView animateWithDuration:0.5
                                  delay:0.05
                 usingSpringWithDamping:0.86
                  initialSpringVelocity:0.4
                                options:UIViewAnimationOptionCurveEaseOut
                             animations:^{
                introTarget.alpha = 1.0;
                introTarget.transform = CGAffineTransformIdentity;
            }
                             completion:nil];
        }
        // Session teardown may still mutate the view hierarchy after this
        // block (SDL drawable churn); reassert visibility one tick later so a
        // late-added game drawable can't cover or hide the library.
        dispatch_async(dispatch_get_main_queue(), ^{
            if (!g_library_controller)
                return;
            library_view().hidden = NO;
            [library_view().superview bringSubviewToFront:library_view()];
            set_metal_drawables_hidden(library_view().window ?: active_window(), YES);
        });
        // Teardown can still straggle past that one tick, so keep re-hiding on
        // a short timer. Bounded, not forever: teardown straggles for a few
        // hundred ms at most, but the library is the screen the app idles on,
        // so a permanent 4 Hz hierarchy walk was burning wake-ups for the
        // entire time the user sits browsing. Sweep for two seconds, then stop.
        if (!g_library_metal_hide_timer) {
            __block NSInteger sweeps = 8;
            g_library_metal_hide_timer = [NSTimer scheduledTimerWithTimeInterval:0.25
                                                                          repeats:YES
                                                                            block:^(NSTimer *timer) {
                if (!g_library_controller || --sweeps <= 0) {
                    [timer invalidate];
                    g_library_metal_hide_timer = nil;
                    if (g_library_controller)
                        set_metal_drawables_hidden(library_view().window ?: active_window(), YES);
                    return;
                }
                set_metal_drawables_hidden(library_view().window ?: active_window(), YES);
            }];
        }
    });
}

void vita3k_ios_update_library(const std::vector<Vita3KIOSGameEntry> &games,
    const Vita3KIOSSettings &settings) {
    const std::vector<Vita3KIOSGameEntry> gamesCopy = games;
    const Vita3KIOSSettings settingsCopy = settings;
    perform_on_main(^{
        publish_core_snapshot(gamesCopy, settingsCopy);
    });
}

void vita3k_ios_hide_library() {
    perform_on_main(^{
        [Vita3KPadNavigator.shared stop];
        set_metal_drawables_hidden(library_view().window ?: active_window(), NO);
        [g_library_controller willMoveToParentViewController:nil];
        [library_view() removeFromSuperview];
        [g_library_controller removeFromParentViewController];
        g_library_controller = nil;
        [g_onboarding_controller.view removeFromSuperview];
        g_onboarding_controller = nil;
        [g_library_metal_hide_timer invalidate];
        g_library_metal_hide_timer = nil;
    });
}

std::optional<Vita3KIOSFrontendAction> vita3k_ios_take_frontend_action() {
    const std::lock_guard lock(g_action_mutex);
    auto action = std::move(g_pending_action);
    g_pending_action.reset();
    return action;
}

int vita3k_ios_load_fps_limit() {
    return 60;
}

bool vita3k_ios_consume_double_buffer_default_migration() {
    static NSString *const key = @"tsubomi.doubleBufferDefaultMigrated";
    NSUserDefaults *defaults = NSUserDefaults.standardUserDefaults;
    if ([defaults boolForKey:key])
        return false;
    [defaults setBool:YES forKey:key];
    return true;
}

void vita3k_ios_present_trophies(const Vita3KIOSTrophyCollection &collection) {
    // Row formatting (grade names, hidden-trophy masking, unlock dates) moved
    // into TsubomiTrophyCollection so the SwiftUI list only lays out strings.
    TsubomiTrophyCollection *bridged = vita3k_ios_internal::bridge_trophies(collection);
    perform_on_main(^{
        [active_window().rootViewController
            presentViewController:[TsubomiTrophyHost trophyViewControllerForCollection:bridged]
                         animated:YES
                       completion:nil];
    });
}

void vita3k_ios_share_file(const std::string &path) {
    NSString *filePath = [NSString stringWithUTF8String:path.c_str()];
    perform_on_main(^{
        NSURL *url = [NSURL fileURLWithPath:filePath];
        UIActivityViewController *share = [[UIActivityViewController alloc] initWithActivityItems:@[url] applicationActivities:nil];
        UIViewController *root = active_window().rootViewController;
        share.popoverPresentationController.sourceView = root.view;
        share.popoverPresentationController.sourceRect = CGRectMake(CGRectGetMidX(root.view.bounds),
            CGRectGetMidY(root.view.bounds), 1, 1);
        [root presentViewController:share animated:YES completion:nil];
    });
}

void vita3k_ios_request_current_trophies() {
    Vita3KIOSFrontendAction action;
    action.kind = Vita3KIOSFrontendActionKind::ShowTrophies;
    queue_action(std::move(action));
}

@interface Vita3KFrametimeGraph : UIView
@property(nonatomic, strong) NSMutableArray<NSNumber *> *samples;
- (void)addSample:(CGFloat)value;
@end

@implementation Vita3KFrametimeGraph
- (instancetype)init {
    self = [super init];
    if (self) {
        self.backgroundColor = UIColor.clearColor;
        self.opaque = NO;
        self.samples = [NSMutableArray array];
    }
    return self;
}
- (void)addSample:(CGFloat)value {
    if (!isfinite(value) || value <= 0)
        return;
    [self.samples addObject:@(value)];
    while (self.samples.count > 60)
        [self.samples removeObjectAtIndex:0];
    [self setNeedsDisplay];
}
- (void)drawRect:(CGRect)rect {
    if (self.samples.count < 2)
        return;
    CGFloat maximum = 16.67;
    for (NSNumber *sample in self.samples)
        maximum = MAX(maximum, MIN((CGFloat)sample.doubleValue, 100.0));
    UIBezierPath *path = [UIBezierPath bezierPath];
    const CGFloat step = CGRectGetWidth(rect) / MAX((CGFloat)self.samples.count - 1, 1);
    [self.samples enumerateObjectsUsingBlock:^(NSNumber *sample, NSUInteger index, __unused BOOL *stop) {
        const CGFloat value = MIN((CGFloat)sample.doubleValue, maximum);
        CGPoint point = CGPointMake(index * step,
            CGRectGetHeight(rect) - (value / maximum) * (CGRectGetHeight(rect) - 2) - 1);
        if (index == 0)
            [path moveToPoint:point];
        else
            [path addLineToPoint:point];
    }];
    UIColor *line = self.traitCollection.userInterfaceStyle == UIUserInterfaceStyleDark
        ? UIColor.whiteColor : UIColor.blackColor;
    [line setStroke];
    path.lineWidth = 1.35;
    path.lineJoinStyle = kCGLineJoinRound;
    path.lineCapStyle = kCGLineCapRound;
    [path stroke];
}
- (void)traitCollectionDidChange:(UITraitCollection *)previousTraitCollection {
    [super traitCollectionDidChange:previousTraitCollection];
    [self setNeedsDisplay];
}
@end

static UIVisualEffectView *g_perf_hud = nil;
static UILabel *g_perf_label = nil;
static Vita3KFrametimeGraph *g_perf_graph = nil;

// Optional live log/console overlay (Settings > Performance overlay > Show
// live log): a bottom-docked scrolling panel of the most recent log lines,
// for reporting bugs without pulling the device off to read tsubomi.log.
// Independent of the FPS/frametime/RAM/battery HUD toggles above, so it is
// updated on every vita3k_ios_update_perf_overlay tick regardless of whether
// that HUD itself is shown.
static UIVisualEffectView *g_log_hud = nil;
static UITextView *g_log_text = nil;

static void update_log_overlay(UIWindow *window) {
    const BOOL show_log = [NSUserDefaults.standardUserDefaults boolForKey:@"vita3k.perf.log"];
    if (!show_log || !window) {
        g_log_hud.hidden = YES;
        return;
    }
    if (!g_log_hud) {
        // Non-interactive: never intercepts the game's touch controls, which
        // stay above it in the window's subview order.
        g_log_hud = [[UIVisualEffectView alloc] initWithEffect:glass_effect(NO)];
        round_continuous(g_log_hud, 10);
        g_log_hud.clipsToBounds = YES;
        g_log_hud.userInteractionEnabled = NO;
        g_log_text = [[UITextView alloc] init];
        g_log_text.backgroundColor = UIColor.clearColor;
        g_log_text.textColor = [UIColor colorWithWhite:0.85 alpha:1.0];
        g_log_text.font = [UIFont monospacedSystemFontOfSize:9 weight:UIFontWeightRegular];
        g_log_text.editable = NO;
        g_log_text.selectable = NO;
        g_log_text.userInteractionEnabled = NO;
        g_log_text.showsVerticalScrollIndicator = NO;
        g_log_text.textContainerInset = UIEdgeInsetsMake(4, 6, 4, 6);
        [g_log_hud.contentView addSubview:g_log_text];
    }
    if (g_log_hud.superview != window) {
        [window addSubview:g_log_hud];
        [window bringSubviewToFront:g_log_hud];
    }
    g_log_hud.hidden = NO;

    const std::vector<std::string> lines = vita3k_ios_recent_log_lines();
    const size_t shown = std::min<size_t>(lines.size(), 40);
    NSMutableString *joined = [NSMutableString string];
    for (size_t i = lines.size() - shown; i < lines.size(); ++i) {
        [joined appendString:[NSString stringWithUTF8String:lines[i].c_str()] ?: @""];
        [joined appendString:@"\n"];
    }
    g_log_text.text = joined;

    const UIEdgeInsets safe = window.safeAreaInsets;
    const CGFloat windowWidth = CGRectGetWidth(window.bounds);
    const CGFloat windowHeight = CGRectGetHeight(window.bounds);
    const CGFloat width = windowWidth - safe.left - safe.right - 16;
    const CGFloat height = MIN(220.0, windowHeight * 0.32);
    g_log_hud.frame = CGRectMake(safe.left + 8, windowHeight - safe.bottom - height - 8, width, height);
    g_log_text.frame = g_log_hud.bounds;
    if (g_log_text.text.length > 0)
        [g_log_text scrollRangeToVisible:NSMakeRange(g_log_text.text.length - 1, 1)];
}

void vita3k_ios_update_perf_overlay(const float guest_fps, const float frametime_ms) {
    perform_on_main(^{
        NSUserDefaults *defaults = NSUserDefaults.standardUserDefaults;
        const BOOL show_fps = [defaults boolForKey:@"vita3k.perf.fps"];
        const BOOL show_frametime = [defaults boolForKey:@"vita3k.perf.frametime"];
        const BOOL show_graph = [defaults boolForKey:@"vita3k.perf.frametimeGraph"];
        const BOOL show_ram = [defaults boolForKey:@"vita3k.perf.ram"];
        const BOOL show_battery = [defaults boolForKey:@"vita3k.perf.battery"];
        UIWindow *window = active_window();
        update_log_overlay(window);
        if ([defaults boolForKey:@"vita3k.perf.hidden"]
            || (!show_fps && !show_frametime && !show_graph && !show_ram && !show_battery)) {
            g_perf_hud.hidden = YES;
            return;
        }

        if (!window)
            return;
        if (!g_perf_hud) {
            // Non-interactive glass: the HUD repaints every second, so live
            // refraction would be wasted cost.
            g_perf_hud = [[UIVisualEffectView alloc] initWithEffect:glass_effect(NO)];
            g_perf_hud.layer.cornerRadius = 12;
            g_perf_hud.clipsToBounds = YES;
            g_perf_hud.userInteractionEnabled = NO;
            g_perf_label = [[UILabel alloc] init];
            g_perf_label.textColor = UIColor.labelColor;
            g_perf_label.font = [UIFont monospacedDigitSystemFontOfSize:12 weight:UIFontWeightSemibold];
            [g_perf_hud.contentView addSubview:g_perf_label];
            g_perf_graph = [[Vita3KFrametimeGraph alloc] init];
            [g_perf_hud.contentView addSubview:g_perf_graph];
        }
        if (g_perf_hud.superview != window) {
            [window addSubview:g_perf_hud];
            [window bringSubviewToFront:g_perf_hud];
        }
        g_perf_hud.hidden = NO;

        NSMutableArray<NSString *> *parts = [NSMutableArray array];
        if (show_fps)
            [parts addObject:[NSString stringWithFormat:@"%.0f FPS", guest_fps]];
        if (show_frametime)
            [parts addObject:frametime_ms > 0
                ? [NSString stringWithFormat:@"%.1f ms", frametime_ms] : @"-- ms"];
        if (show_ram) {
            task_vm_info_data_t vm_info{};
            mach_msg_type_number_t count = TASK_VM_INFO_COUNT;
            if (task_info(mach_task_self(), TASK_VM_INFO,
                    reinterpret_cast<task_info_t>(&vm_info), &count) == KERN_SUCCESS)
                [parts addObject:[NSString stringWithFormat:@"%.0f MB", vm_info.phys_footprint / (1024.0 * 1024.0)]];
        }
        if (show_battery) {
            // Monitoring has to be on before batteryLevel returns anything but
            // -1, and it used to be enabled in the UIKit library view's
            // initialiser. That view is gone, so own it here: this is the only
            // place that reads the level, and enabling it is idempotent.
            //
            // Granularity is the OS's to decide. UIDevice is documented as
            // accurate to within 5%, and there is no public API that reports
            // finer, so round to whole percent and show what the system gives
            // rather than inventing precision.
            UIDevice *device = UIDevice.currentDevice;
            if (!device.batteryMonitoringEnabled)
                device.batteryMonitoringEnabled = YES;
            const float level = device.batteryLevel;
            if (level >= 0)
                [parts addObject:[NSString stringWithFormat:@"%.0f%%", level * 100.0f]];
        }
        g_perf_label.text = [parts componentsJoinedByString:@"  ·  "];
        [g_perf_label sizeToFit];
        const CGFloat width = MAX(CGRectGetWidth(g_perf_label.bounds) + 20, show_graph ? 170.0 : 0.0);
        const CGFloat height = show_graph ? 58.0 : 24.0;
        const UIEdgeInsets safe = window.safeAreaInsets;
        const CGFloat windowWidth = CGRectGetWidth(window.bounds);
        const CGFloat windowHeight = CGRectGetHeight(window.bounds);
        const BOOL portrait = windowHeight > windowWidth;
        // User-placed position from the layout editor (normalized center, per
        // orientation); defaults: below the letterboxed game image in
        // portrait, top-left in landscape.
        NSString *keyX = portrait ? @"tsubomi.perfPos.portrait.x" : @"tsubomi.perfPos.landscape.x";
        NSString *keyY = portrait ? @"tsubomi.perfPos.portrait.y" : @"tsubomi.perfPos.landscape.y";
        CGFloat centerX;
        CGFloat centerY;
        if ([defaults objectForKey:keyX] && [defaults objectForKey:keyY]) {
            centerX = [defaults doubleForKey:keyX] * windowWidth;
            centerY = [defaults doubleForKey:keyY] * windowHeight;
        } else if (portrait) {
            const CGFloat gameHeight = windowWidth * 544.0 / 960.0;
            centerX = windowWidth / 2;
            centerY = safe.top + gameHeight + height / 2 + 10;
        } else {
            centerX = safe.left + 10 + width / 2;
            centerY = safe.top + 6 + height / 2;
        }
        centerX = std::clamp(centerX, safe.left + width / 2, windowWidth - safe.right - width / 2);
        centerY = std::clamp(centerY, safe.top + height / 2, windowHeight - safe.bottom - height / 2);
        g_perf_hud.bounds = CGRectMake(0, 0, width, height);
        g_perf_hud.center = CGPointMake(centerX, centerY);
        g_perf_label.frame = CGRectMake(10, 3, width - 20, 18);
        g_perf_graph.hidden = !show_graph;
        g_perf_graph.frame = CGRectMake(10, 27, width - 20, 25);
        if (show_graph)
            [g_perf_graph addSample:frametime_ms];
    });
}

void vita3k_ios_hide_perf_overlay() {
    perform_on_main(^{
        [g_perf_hud removeFromSuperview];
        g_perf_hud = nil;
        g_perf_label = nil;
        g_perf_graph = nil;
        [g_log_hud removeFromSuperview];
        g_log_hud = nil;
        g_log_text = nil;
    });
}

void vita3k_ios_report_import_result(const std::string &message, const bool success) {
    NSString *text = [NSString stringWithUTF8String:message.c_str()] ?: @"Import finished";
    perform_on_main(^{
        [TsubomiLibraryStateBridge setBusyMessage:nil];
        // Onboarding used to render its own inline status for this. The
        // SwiftUI flow instead shows "Installed" from FirmwareState once the
        // package actually lands, and failures still reach the user through
        // the alert below - which is the more accurate signal anyway, since a
        // wrong-package import "succeeds" as a file operation.
        if (success) {
            // The toast owns its own dismissal timer in LibraryState.
            [TsubomiLibraryStateBridge showStatusMessage:text];
            if ([text localizedCaseInsensitiveContainsString:@"license"])
                present_alert(@"License installed", text);
        } else {
            // Keep the precise installer detail on screen until dismissed.
            NSString *title = [text localizedCaseInsensitiveContainsString:@"save"]
                ? @"Save transfer failed"
                : @"Import failed";
            present_alert(title, text);
        }
    });
}

void vita3k_ios_show_boot_error(const std::string &message) {
    NSString *text = [NSString stringWithUTF8String:message.c_str()] ?: @"The game could not start.";
    perform_on_main(^{
        [TsubomiLibraryStateBridge setBusyMessage:nil];
        present_alert(@"Couldn’t start game", text);
    });
}

void vita3k_ios_set_jit_available(const bool available) {
    perform_on_main(^{
        g_jit_available = available;
        [TsubomiLibraryStateBridge setJITAvailable:available];
    });
}

void vita3k_ios_prompt_license_import(const std::string &title_id) {
    NSString *identifier = [NSString stringWithUTF8String:title_id.c_str()] ?: @"this title";
    perform_on_main(^{
        UIViewController *root = active_window().rootViewController;
        if (!root)
            return;
        UIAlertController *prompt = [UIAlertController
            alertControllerWithTitle:@"License required?"
                             message:[NSString stringWithFormat:@"%@ has no NoNpDrm license installed. If this is a NoNpDrm dump, import its work.bin now.", identifier]
                      preferredStyle:UIAlertControllerStyleAlert];
        [prompt addAction:[UIAlertAction actionWithTitle:@"Import work.bin"
                                                   style:UIAlertActionStyleDefault
                                                 handler:^(__unused UIAlertAction *action) { present_license_picker(); }]];
        [prompt addAction:[UIAlertAction actionWithTitle:@"Not now" style:UIAlertActionStyleCancel handler:nil]];
        [root presentViewController:prompt animated:YES completion:nil];
    });
}

void vita3k_ios_configure_audio_session() {
    NSError *error = nil;
    AVAudioSession *session = AVAudioSession.sharedInstance;
    // Playback so audio keeps running with the mute switch on and the audio
    // unit is actually scheduled; MixWithOthers keeps us polite.
    if (![session setCategory:AVAudioSessionCategoryPlayback
                         mode:AVAudioSessionModeDefault
                      options:AVAudioSessionCategoryOptionMixWithOthers
                        error:&error]) {
        LOG_ERROR("iOS audio session setCategory failed: {}",
            error.localizedDescription.UTF8String ?: "unknown");
        error = nil;
    }
    if (![session setPreferredSampleRate:48000 error:&error]) {
        LOG_WARN("iOS audio session preferred sample rate failed: {}",
            error.localizedDescription.UTF8String ?: "unknown");
        error = nil;
    }
    constexpr NSTimeInterval preferredBufferDuration = 1024.0 / 48000.0;
    if (![session setPreferredIOBufferDuration:preferredBufferDuration error:&error]) {
        LOG_WARN("iOS audio session preferred buffer duration failed: {}",
            error.localizedDescription.UTF8String ?: "unknown");
        error = nil;
    }
    if (![session setActive:YES error:&error]) {
        LOG_ERROR("iOS audio session activation failed: {}",
            error.localizedDescription.UTF8String ?: "unknown");
    } else {
        LOG_INFO("iOS audio session active (Playback), sample rate {} Hz, I/O buffer {:.2f} ms",
            session.sampleRate, session.IOBufferDuration * 1000.0);
    }
}

void vita3k_ios_pump_runloop(const double seconds) {
    // On the main thread (where SDL runs main() on iOS) the run loop owns the
    // UIKit event/timer sources, so running it for `seconds` keeps scrolling,
    // sliders, and glass animations smooth instead of the blind SDL_Delay that
    // starved them. returnAfterSourceHandled:false makes it block the full
    // interval rather than spinning after each event. Off the main thread the
    // run loop has no sources and would return instantly, so sleep instead to
    // avoid a busy loop.
    if (NSThread.isMainThread)
        CFRunLoopRunInMode(kCFRunLoopDefaultMode, seconds, false);
    else
        [NSThread sleepForTimeInterval:seconds];
}

void vita3k_ios_report_settings_result(const std::vector<std::string> &restart_required) {
    NSMutableArray<NSString *> *labels = [NSMutableArray arrayWithCapacity:restart_required.size()];
    for (const auto &label : restart_required)
        [labels addObject:[NSString stringWithUTF8String:label.c_str()]];
    perform_on_main(^{
        if (labels.count == 0)
            return;
        // Restart-required settings are reported through the same toast the
        // library uses for import results, rather than a modal alert: the
        // change has already been applied and saved, so this is information,
        // not a decision.
        [TsubomiLibraryStateBridge showStatusMessage:
            [NSString stringWithFormat:@"Restart Tsubomi to apply: %@",
                [labels componentsJoinedByString:@", "]]];
    });
}
